openapi: 3.0.0
servers:
  - url: 'https://mh.scottnet.dev/api'
info:
  description: >-
    The unofficial public API for Miner's Haven
  version: 1.0.0
  title: Miner's Haven OpenAPI
  license:
    name: Apache-2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: pet
    description: Everything about your Pets
  - name: store
    description: Access to Petstore orders
  - name: user
    description: Operations about user
paths: 
  /collection/{id}:
    get:
      description: yurr
    responses:
      '200':
        description: success
        content: 
          